// Real SHG directory data, manually captured from the government NRLM portal
// (preprodmis.lokos.in). This mirrors the site's own hierarchy: State -> District
// -> Block -> Grampanchayat -> Village -> SHG Group -> member count.
//
// IMPORTANT: only these have real, verified group-level data (member counts
// cross-checked against the site's own page totals — all match exactly):
//   Cachar > Silchar > Berenga > Berenga Part 1 (174) / Berenga Part 2 (440)
//   Cachar > Silchar > Madhurbond > Silchar X (301) / Silchar XI (377)
//   Cachar > Silchar > Baghadahar Borjurai > Berenga Part 3 (472) /
//     Berenga Part 4 (347) / Berenga Part 5 (367)
//   Cachar > Silchar > Kanakpur > Kanakpur Part 1 (235) / Kanakpur Part 2 (713)
//   Cachar > Silchar > Ambikapur > Ambikapur Part 1 (121) / Part 4 (41) /
//     Part 5 (257) / Part 7 (169) / Part 8 (710)
//     (villages on the source site are numbered I, IV, V, VII, VIII — II, III,
//     VI don't exist there, so Parts 2/3/6 are intentionally absent)
// Note: a few individual groups show 0 members in the source data itself
// (e.g. "LOTUS SHG", "PRATIVA SHG", "AMON SHG", "ABC", "SARODA SHG") —
// transcribed as-is, not an error here.
// Every other Block / Grampanchayat listed below is real (from the site's own
// summary tables) but has no group-level data filled in yet, so it will show as
// empty in the picker — that's intentional, not a bug. Use manual typing for those
// until more villages get added here.

export const SHG_DIRECTORY = {
  Assam: {
    Cachar: {
      // Real block list for Cachar district (from the site's block-summary table).
      // Only Silchar has Grampanchayat/Village/Group data filled in so far.
      Banskandi: {},
      Binnakandi: {},
      Borjalenga: {},
      Borkhola: {},
      Kalain: {},
      Katigora: {},
      Lakhipur: {},
      Narsingpur: {},
      Palonghat: {},
      Rajabazar: {},
      Salchapra: {},
      Silchar: {
        // Real Grampanchayat list for Silchar block. Only Berenga has
        // village/group data filled in so far.
        Ambikapur: {
          "Ambikapur Part 1": [
            ["BANDHANA SHG", 12],
            ["BRIGHT SHG", 12],
            ["LILY S.H.G", 12],
            ["M/S JOY GURU SHG", 12],
            ["RADHABALLAB SHG", 13],
            ["SANJIBANI SELF HELP GROUP", 13],
            ["SATARUPA S.H.G", 15],
            ["SHINLELMA NUPI LOOP", 8],
            ["IMOONU NUPEE LOOP SHG", 12],
            ["PRIYADARSHANE SHG", 12],
          ],
          "Ambikapur Part 4": [
            ["PADDHA S.H.G.", 10],
            ["RUPALI S.H.G", 10],
            ["SARADA S.H.G", 10],
            ["SHIVA SHG", 11],
          ],
          "Ambikapur Part 5": [
            ["ASHIRBAD SHG", 12],
            ["AYUSH S.H.G", 11],
            ["BIDHYA SHG", 11],
            ["CHANDRIMA SHG", 13],
            ["CHITRANGADA SHG", 12],
            ["GANGA S.H.G", 8],
            ["GITANJALI S.H.G.", 10],
            ["JIBON JYOTI SHG", 15],
            ["LAXMI S.H.G", 10],
            ["M/S BIPODTARINI SHG", 11],
            ["M/S JONONI SHG", 12],
            ["MAA DURGA S.H.G", 12],
            ["MAHAMAYA SHG", 10],
            ["NARAYANI S.H.G", 9],
            ["PUJA S.H.G", 10],
            ["RADHE SHYAM S.H.G", 6],
            ["RADHE SHYAM SHG", 11],
            ["ROSE SHG", 10],
            ["RUPASHREE SHG", 10],
            ["BANAMALI MAHILA SELF HELP GROUP BUDHURAIL", 8],
            ["BHAGINI NIVEDITA SHG", 9],
            ["KANIKA SHG", 8],
            ["M/S BINAPANI SHG", 11],
            ["M/S MAHALAXMI SHG", 9],
            ["MOTHER TERESA MOHILA S.H.G", 9],
            ["NABARUPA WOMAN SHG", 0],
          ],
          "Ambikapur Part 7": [
            ["APARAJITA SHG", 14],
            ["BHARAT MATA SHG", 18],
            ["BIJOY LAXMI SHG", 10],
            ["CHANDRAMA S H G", 15],
            ["KIRON S.H.G", 9],
            ["PUJA S.H.G", 10],
            ["PURBA CHANDRAPUR MOHILA SOMITI", 11],
            ["ROSHNI SHG", 14],
            ["SURYA SHG", 12],
            ["JONAKI SELF HELP GROUP", 12],
            ["BHARATI SHG", 12],
            ["DRUBHAJYOTI SHG", 11],
            ["M/S SEBA MOHILA SHG", 12],
            ["PROTIBHA S H G", 0],
            ["SARADA SELF HELP GROUP", 9],
            ["SARODA SHG", 0],
          ],
          "Ambikapur Part 8": [
            ["NAYANA S H G", 13],
            ["ABC", 0],
            ["ALO SHG", 12],
            ["ANAPURNA SHG", 10],
            ["APRAJITA SHG", 10],
            ["B.M.D.C MAHILA SAMITI DEVCOM", 12],
            ["BHAGASREE SELF HELP GROUP", 13],
            ["BIJAYINI MOHILA S.H.G", 13],
            ["BINAPANI SHG", 12],
            ["BOBITA SINHA", 12],
            ["BOROMA SHG", 12],
            ["DURGA SHAKTI SHG", 10],
            ["JAGANNATH SHG", 12],
            ["KALPATARU SHG", 12],
            ["KRISHNA SHG", 11],
            ["KUSHI SHG", 11],
            ["M/S RANI SHG", 10],
            ["MAA BHAVANI S.H.G.", 12],
            ["MAA KALI S.H.G", 8],
            ["MATRI SHAKTI SHG", 12],
            ["MONJURI SELF HELP GROUP", 9],
            ["NARI ANUPERONA SHG", 13],
            ["NARISHAKTI SHG", 12],
            ["PATANJALI S.H.G.", 9],
            ["RADHA GOBINDA SHG", 12],
            ["RADHA MADHAB SHG", 12],
            ["RADHA SHG", 14],
            ["SAHASHI MOHILA S H H", 12],
            ["SARADAMONI S.H.G", 10],
            ["SHAKTI SHG", 10],
            ["SHIBAM SHG", 12],
            ["SHIV SHAKTI SHG", 12],
            ["SHRI RADHA SHG", 10],
            ["TRINAYANI MAHILA S.H.G GROUP", 13],
            ["DOORADARSHI S H G", 13],
            ["ASHA JYOTI S H G", 12],
            ["BARSHA SHG", 11],
            ["BHAVANI S.H.G.", 13],
            ["BISHNUPRIYA S.H.G.", 7],
            ["GAKUL SHG", 6],
            ["JAMUNA SHG", 12],
            ["JEEBAN JYOTI SHG", 10],
            ["JYOTI SHG", 12],
            ["LEIMA MARUP SHG", 11],
            ["MAA ANANDAMOYEE S.H.G", 12],
            ["MAYUREESHG", 10],
            ["MOON S H G", 2],
            ["NABARUPA WOMAN S H G", 12],
            ["NIRU SHG", 5],
            ["NOVOJYOTI S.H.G", 11],
            ["PADMASHRI S.H.G.", 10],
            ["PANTHOIBI SINLUP SHG", 11],
            ["PROVATI SHG", 10],
            ["PUSPASHRI SHG", 10],
            ["R. K. WOMAN SELF HELP GROUP", 12],
            ["RISING SELF HELP GROUP", 10],
            ["SARADA SHG", 8],
            ["SARASWATI SHG", 11],
            ["SHANTI SUNDAR SHG", 12],
            ["SHRI LAKHI S.H.G", 11],
            ["SUFALA SHG", 11],
            ["SUMILON ATMO SAHAYAK DOL", 12],
            ["SUSMITA SELF HELP GROUP", 9],
            ["SWARNAMOYEE SELF HELP GROUP", 15],
            ["UDIYAMAN SHG", 12],
            ["UJJAINI SELF HELP GROUP", 10],
          ],
        },
        "Baghadahar Borjurai": {
          "Berenga Part 3": [
            ["SAMRIDDI SHG", 11],
            ["BEST SHG", 9],
            ["FRIEND SHG", 10],
            ["JANIFAN SHG", 9],
            ["JIBAN TARA SHG", 10],
            ["JOBA SHG", 10],
            ["LOTUS SHG", 0],
            ["LUCKY SHG", 13],
            ["M/S SWARNA TARA S.H.G", 20],
            ["MAMUNI S.H.G", 12],
            ["MOON SELF HELP GROUP", 10],
            ["OLD SHG", 0],
            ["ORPON SELF HELP GROUP", 7],
            ["PIEARA SELF HELP GROUP", 9],
            ["PURNIMA SHG", 12],
            ["ROSNE SHG", 9],
            ["RUPALI SHG", 13],
            ["SABINA SHG", 12],
            ["SADDAM SHG", 9],
            ["SHIB DURGA SELF HELP GROUP", 15],
            ["SUFALA SHG", 10],
            ["SUN SHG", 10],
            ["SIMRAN SHG", 12],
            ["BABY SELF HELP GROUP", 10],
            ["DIMOND SELF HELP GROUP", 8],
            ["ELIDE SELF HELP GROUP", 10],
            ["GANDHARAJ SHG", 8],
            ["HINDUSTAN SHG", 11],
            ["JANANI SHG", 10],
            ["JOYMILON SHG", 10],
            ["KABERI SHG", 11],
            ["KALYANI SELF HELP GROUP", 4],
            ["KUSHI SELF HELP GROUP", 9],
            ["M/S AMRITA SHG", 10],
            ["M/S MAJONI SHG", 9],
            ["M/S NAZIHA SHG", 12],
            ["M/S VIJAYA SHG", 17],
            ["M/S VJAYA SHG", 11],
            ["NARI KALYAN SHG", 11],
            ["PURBO ASHA SHG", 10],
            ["RESHMA SELF HELP GROUP", 13],
            ["RIYA SHG", 11],
            ["SAKHI SHG", 13],
            ["SHUBAM SELF HELP GROUP", 10],
            ["SHYMALA SHG", 10],
            ["SONIA SELF HELP GROUP", 12],
          ],
          "Berenga Part 4": [
            ["DEPALE SHG", 10],
            ["JASMIN SHG", 12],
            ["KAMOLA SHG", 12],
            ["KUM KUM SHG", 11],
            ["LOVELY SHG", 13],
            ["MAA DURGA SELF HELP GROUP", 10],
            ["MAHILA SHG", 11],
            ["MODUMITA SHG", 10],
            ["RANUKA SHG", 10],
            ["SHANI DEV SELF HELP GROUP", 10],
            ["SUNALY SELF HELP GROUP", 10],
            ["UNNATI SHG", 12],
            ["BIPLAB SELF HELP GROUP", 10],
            ["CENTRAL SELF HELP GROUP", 10],
            ["CLASSMATE SHG", 9],
            ["DELUX SELF HELP GROUP", 10],
            ["KALYAN JYOTY SHG", 10],
            ["KAMOLA SHG", 14],
            ["LOTUS SELF HELPGROUP", 10],
            ["LOTUS SHG", 13],
            ["M/S AFRIN SELF HELP GROUP", 14],
            ["M/S JAI GURU SHG", 10],
            ["M/S NEW KIRON SHG", 13],
            ["M/S SHIB SHAKTI SHG", 15],
            ["MADHUMITA SHG", 11],
            ["MAMOTAZ SELF HELP GROUP", 10],
            ["MOHARANI SHG", 13],
            ["NABARUPA SHG", 13],
            ["RANI MAA SHG", 10],
            ["SAHARA SELF HELP GROUP", 11],
            ["SHABNAM SELF HELP GROUP", 10],
          ],
          "Berenga Part 5": [
            ["AKASH SHG", 12],
            ["BEAUTY SELF HELP GROUP", 10],
            ["FLOWER SHG", 10],
            ["M/S MEHAZ S.H.G", 12],
            ["M/S ROSE S.H.G", 12],
            ["MAHI SHG", 10],
            ["NABA UDAY S.H.G", 11],
            ["NABO VIKASH SHG", 12],
            ["SHYAMALA ATMA SAHAYAK DAL", 10],
            ["SUKTARA SHG", 10],
            ["SUMAN SHG", 12],
            ["TRINAYANI SHG", 10],
            ["UMA SELF HELP GROUP", 11],
            ["ANANDA SHREE SHG", 11],
            ["ASHA SHG", 9],
            ["ASHAPURNA SHG", 12],
            ["FREEDOM SELF HELP GROUP", 12],
            ["GOLDEN SELF HELP GROUP", 11],
            ["ISLAMIA SHG", 12],
            ["JIBAN SHREE SHG", 13],
            ["KUSBU SHG", 31],
            ["LUCKY SHG BERENGA V", 0],
            ["MAYABATI SHG", 15],
            ["MOHA MILAN S H G", 12],
            ["MOMI SELF HELP GROUP", 10],
            ["PRATIVA SHG", 0],
            ["RAJDEEP SELF HELP GROUP", 10],
            ["SADIYA SELF HELP GROUP", 11],
            ["SANCHITA SELF HELP GROUP", 12],
            ["SONCHITA SHG", 11],
            ["SUKTARA SELF HELP GROUP", 10],
            ["SUNLIGHT SELF HELP GROUP", 12],
            ["SURAKSHA SELF HELP GROUP", 11],
            ["SWARNA LAKSHMI SHG", 0],
          ],
        },
        Berenga: {
          "Berenga Part 1": [
            ["ANJALI SHG", 12],
            ["FORIDA SHG", 10],
            ["HASNA S.H.G", 11],
            ["HONUMAN SELF HELP GROUP", 13],
            ["JUHI SHG", 14],
            ["KUSHI SHG", 11],
            ["MADHUMITA SELF HELP GROUP", 11],
            ["MAHEK S.H.G", 16],
            ["MOON SHG", 11],
            ["RAKHI SELF HELP GROUP", 10],
            ["RATNAGIRI SELF HELP GROUP", 12],
            ["RED ROSE SELF HELP GROUP", 12],
            ["RUPALY SHG", 11],
            ["SUHANA SHG", 10],
            ["VARSHA SHG", 10],
          ],
          "Berenga Part 2": [
            ["ABIDA SHG", 10],
            ["ALI SAHA SHG", 6],
            ["ARMIN S.H.G", 12],
            ["BEST SHG", 10],
            ["DURGA MANDAL SELF HELF GROUP", 13],
            ["GREEN BIPLOB SHG", 13],
            ["GULAF SELF HELP GROUP", 13],
            ["JANNAT SHG", 10],
            ["JANOPRIYA MOHILA SELF HELP GROUP BERENGA PT2", 10],
            ["JASMIN SHG", 8],
            ["JORNA SELF HELP GROUP", 10],
            ["JOY LAKHI SELF HELP GROUP", 12],
            ["LAXMI SHG", 12],
            ["M/S. ROYAL SELF HELP GROUP", 10],
            ["MILON SELF HELP GROUP", 12],
            ["MORIOM SHG", 7],
            ["MUSKAN", 12],
            ["NABO RATNA SELF HELP GROUP", 10],
            ["RADHA RANI SHG", 15],
            ["REMA S.H.G", 10],
            ["ROSE SHG", 10],
            ["ROSHNI SELF HELP GROUP", 10],
            ["ROSNI SELF HELP GROUP", 10],
            ["RUHI SHG", 9],
            ["RUHON S.H.G", 11],
            ["RUMI SELF HELP GROUP", 11],
            ["RUMI SHG", 10],
            ["SADIYA SHG", 10],
            ["SAFALI SELF HELP GROUP", 14],
            ["SAHANAJ SELF HELP GROUP", 10],
            ["SAHIL S.H.G", 13],
            ["SAMA SELF HELP GROUP", 11],
            ["SHIBAM SELF HELP GROUP", 12],
            ["SHRISHTI SHG", 10],
            ["SNEHA SELP HELF GROUP", 11],
            ["SOHELI SHG", 12],
            ["SONY S.H.G", 10],
            ["SUHAN SELF HELP GROUP", 10],
            ["SUN SELF HELP GROUP", 11],
            ["TAMANNA SHG", 10],
            ["UJJAL SELF HELP GROUP", 10],
          ],
        },
        Bhajantipur: {},
        Ghungoor: {},
        Kanakpur: {
          "Kanakpur Part 1": [
            ["AMON SHG", 0],
            ["HARI OM SHG", 0],
            ["JOBA SHG", 2],
            ["M/S MAHI SHG", 12],
            ["MAYA S.H.G", 13],
            ["SANIYA SHG", 12],
            ["SARODA SHG", 1],
            ["SHAPALI S.H.G.", 7],
            ["SHONA MAA SELF HELP GROUP", 12],
            ["SRIRAM SELF HELP GROUP", 20],
            ["STAR SHG", 12],
            ["UNNATI SHG", 12],
            ["TEN VIGILANCE SHG", 25],
            ["AGRAGRAMI MOHILA SHG", 10],
            ["DASHABHUJA SHG", 11],
            ["JOYGURU SHG", 10],
            ["KUSHI SELF HELF GROUP", 2],
            ["MAA MONI SHG", 12],
            ["MUNNA TANTI JAYA TANTI", 10],
            ["PARIJAT ATMASAHAYAK GUSTI", 21],
            ["SISTER NIBEDITA SHG", 11],
            ["SWARNA MUDRA SHG", 10],
            ["SWASTIKA MOHILA SHG", 10],
          ],
          "Kanakpur Part 2": [
            ["AAGOMONI S.H.G", 14],
            ["BIPONADNASINI S.H.G", 21],
            ["GANAPATI SELF HELP GROUP", 15],
            ["GANDHARAJ SHG", 23],
            ["GULAP SHG", 14],
            ["JOY DURGA SELF HELP GROUP", 10],
            ["LUCKY SHG", 10],
            ["M/S HARI OM SHG", 18],
            ["M/S JOMUNA SHG", 13],
            ["M/S OMKAR SHG", 10],
            ["M/S UMA SHG", 10],
            ["MAMTAJ SHG", 12],
            ["MONMOHINI MAHILA SHG", 14],
            ["RADHA RANI SHG", 8],
            ["RAJLAKSHMI SHG", 2],
            ["SAATI SHG", 16],
            ["SREE GOPAL SHG", 11],
            ["SURJA SELF HELP GROUP", 10],
            ["SURJYAMUKHI SELF HELP GROUP", 0],
            ["AGRAGAMI SHG", 10],
            ["ALORON SELF HELP GROUP", 7],
            ["AMON SHG", 10],
            ["ANNAPURNA S H G", 10],
            ["BALAJI SHG", 16],
            ["BIPODNASHINI SHG", 3],
            ["BOROMA SHG", 4],
            ["GEETA SELF GROUP", 10],
            ["JEEBAN BHARATI SHG", 2],
            ["JOY GURU MOHILA SHG", 10],
            ["JOYGURU SHG", 20],
            ["LAKHI NARAYAN S.H.G.", 13],
            ["M/S SHYANA SHG", 12],
            ["MAA SANTOSHI S H G", 7],
            ["MAHA LAKHI SHG", 19],
            ["MAHAPROBHU S.H.G.", 21],
            ["MANASHA MOHILA SHG", 8],
            ["MS AMON SHG", 12],
            ["NARAYANI SHG", 22],
            ["NAVAJEEBAN S H G", 7],
            ["NETAJI ATMOSAHAYAK GOSTHI", 12],
            ["PROGOTI MOHILA SELF HELP GROUP", 10],
            ["PROGOTI SELF HELP GROUP", 14],
            ["RADHARAMAN SELF HELP GROUP", 11],
            ["RADHARANI SHG", 10],
            ["RADHESHYAM SELF HELP GROUP", 0],
            ["RAJ SHG", 0],
            ["RAMDHANU SHG", 6],
            ["RAMKRISHNA SELF HELP GROUP", 0],
            ["RAMKRISHNA SHG", 6],
            ["SARATPALLYUTTRANCHAL ATMASAHAUYAK", 12],
            ["SHRIMA S H G", 26],
            ["SHYAMANANDA SELF HELP GROUP", 7],
            ["SHYAMANANDA SELF HELP GROUP", 0],
            ["SIMA MAHILA S.H.G", 20],
            ["SONGITHA DEVI SHG", 8],
            ["SREEMA SHG", 14],
            ["SRINATH SELF HELP GROUP", 16],
            ["SWARNA MOYEE SHG", 20],
            ["SWASTIKA SHG", 18],
            ["TARAKESWAR SHG", 9],
            ["TRINAYANI SHG", 19],
            ["TULSI SELF HELP GROUP", 0],
            ["UNNAYAN MAHILA SELF HELP GROUP", 12],
            ["VIVEKANANDA MOHILA SHG", 9],
          ],
        },
        Madhurbond: {
          "Silchar X": [
            ["ASHA S.H.G.", 11],
            ["HENA S.H.G", 12],
            ["HONEY S.H.G", 10],
            ["JANNOT S.H.G.", 15],
            ["JEEVIKA SELF HELP GROUP", 14],
            ["JONALI SHG", 10],
            ["KORUNA S.H.G", 11],
            ["M/S. FARHIN SHG", 17],
            ["MAMPI S.H.G", 9],
            ["MARIN SHG", 10],
            ["MINA S.H.G.", 12],
            ["PROGOTI SELF HELP GROUP", 11],
            ["QUEEN S.H.G", 11],
            ["ROSE S.H.G", 18],
            ["RUHI SHG", 10],
            ["SIMA SHG", 12],
            ["SUN SHG", 10],
            ["TANJIMA S.H.G.", 11],
            ["VIKASH SHG", 10],
            ["VISHAL S.H.G", 11],
            ["FATIMA SELF HELP GROUP", 10],
            ["MAYA SHG", 15],
            ["MOON SELF HELP GROUP", 11],
            ["MUSKAN SELF HELP GROUP", 11],
            ["NAZIRA SELF HELP GROUP", 10],
            ["SAMAJ KAILYAN SELF HELP GROUP", 9],
          ],
          "Silchar XI": [
            ["ANNA SHG", 11],
            ["ARUHI SHG", 7],
            ["CACHAR SHG", 13],
            ["CHAND SHG", 13],
            ["FARHAN SHG", 8],
            ["HARINI SHG", 9],
            ["HAZARI S.H.G", 21],
            ["IMPRESSION SHG", 10],
            ["ISHA SHG", 12],
            ["KALYAN SHG", 10],
            ["KOLPONA SHG", 8],
            ["KUSHI S.H.G.", 11],
            ["KUSUM SHG", 13],
            ["LUCKY SHG", 8],
            ["MANAB KALYAN SHG", 7],
            ["MISHTI SHG", 12],
            ["MODHUMETA SHG", 12],
            ["NARGIS SELF HELP GROUP", 12],
            ["NARI KALYAN SHG", 10],
            ["PAROSE S.H.G", 9],
            ["PROJAPATI SELF HELP GROUP", 12],
            ["RIYA SHG", 7],
            ["ROSHNI S.H.G", 10],
            ["SATHI SHG", 11],
            ["STAR S.H.G", 23],
            ["SWEET SHG", 6],
            ["DAYAL SELF HELP GROUP", 10],
            ["ENERGY SHG", 13],
            ["GOLD SHG", 16],
            ["JOTI SHG", 20],
            ["SANTI S.H.G", 15],
            ["TEN STAR S.H.G", 18],
          ],
        },
        Meherpur: {},
        "Neairgram Bagpur": {},
        "Ramnagar Tarapur": {},
        Tarapur: {},
        Tupkhana: {},
      },
      Sonai: {},
      Tapang: {},
      Udharbond: {},
    },
  },
};

// Flattens the directory into a single searchable list:
// [{ name, members, path: "Village, Grampanchayat, Block, District, State" }, ...]
// Used to power the "type to search" autocomplete on the SHG name field.
export function flattenDirectory(dir = SHG_DIRECTORY) {
  const results = [];
  function walk(node, crumbs) {
    if (Array.isArray(node)) {
      // node is a list of [groupName, memberCount] tuples at a Village level
      node.forEach(([name, members]) => {
        results.push({ name, members, path: crumbs.slice().reverse().join(", ") });
      });
      return;
    }
    if (node && typeof node === "object") {
      Object.entries(node).forEach(([key, child]) => walk(child, [key, ...crumbs]));
    }
  }
  walk(dir, []);
  return results;
}
